# Site settings
title: Nikhil Kalyanpur
email: nik.kalyanpur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://nkalyanpur.github.io" # the base hostname & protocol for your site
github_username:  nkalyanpur
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
