# Site settings
title: Calvin Thrall
email: cthrall@utexas.edu
logo: /assets/Thrall_Calvin_Pic.jpg
description: > # this means to ignore newlines until "baseurl:"
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://calvinthrall.github.io" # the base hostname & protocol for your site
twitter_username: calvinthrall
github_username:  calvinthrall
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
