# Site settings
title: Calvin Thrall
email: cthrall@utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  Hi there! I'm a PhD student in the Department of Government at The University of Texas at Austin.
  My research interests are mainly in international political economy; I am particularly interested in the
  impact of cross-border capital flows on domestic political institutions.
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://calvinthrall.github.io" # the base hostname & protocol for your site
twitter_username: calvinthrall
github_username:  calvinthrall
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
